version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "kufar"
      POSTGRES_USER: "dbeekeeper"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    restart: always
  web:
    image: ksusha3011neprostopeshka/alakufar_web:latest
    command: python /usr/src/alakufar/manage.py runserver 0.0.0.0:8000
    environment:
      WAIT_HOSTS: postgres:5432
    ports:
      - 8000:8000
    depends_on:
      - db